# This is a basic workflow to help you get started with Actions

name: snowflake-macos

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: setup php
          uses: shivammathur/setup-php@v2
          with:
            php-version: 7.2
            extensions: pdo, json
          
        - name: get source
          run: git clone https://github.com/snowflakedb/pdo_snowflake.git
        
        
        - name: Build PDO Driver
          env: 
            SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
            SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
            SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
            SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.SNOWFLAKE_TEST_WAREHOUSE }}
            SNOWFLAKE_TEST_DATABASE: ${{ secrets.SNOWFLAKE_TEST_DATABASE }}
            SNOWFLAKE_TEST_SCHEMA: ${{ secrets.SNOWFLAKE_TEST_SCHEMA }}
            SNOWFLAKE_TEST_ROLE: ${{ secrets.SNOWFLAKE_TEST_ROLE }}
          run: |
            export RUN_COVERAGE=1
            export PHP_HOME=/usr/local
            ./scripts/build_pdo_snowflake.sh
            $PHP_HOME/bin/php -dextension=modules/pdo_snowflake.so -m | grep pdo_snowflake
            cp ../config/parameters.json ./
            python ../scripts/set_secrets.py ./parameters.json
            ./scripts/env.sh && env | grep SNOWFLAKE_TEST > testenv.ini
            REPORT_EXIT_STATUS=1 NO_INTERACTION=true make test || :
            echo "===========parseing test result============"
            python ../scripts/check_result.py ./tests
          working-directory: /Users/runner/work/ATA-POC-ODBC/ATA-POC-ODBC/pdo_snowflake
