# This is a basic workflow to help you get started with Actions

name: snowflake-macos

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #- uses: actions/checkout@v2
        - name: setup php
          uses: shivammathur/setup-php@v2
          with:
            php-version: 7.2
            extensions: pdo, json
          
        - name: get source
          run: git clone https://github.com/snowflakedb/pdo_snowflake.git
        
        
        - name: Build PDO Driver
          run: |
            export RUN_COVERAGE=1
            export PHP_HOME=/usr/local
            which php
            ls
            ./scripts/build_pdo_snowflake.sh
            $PHP_HOME/bin/php -dextension=modules/pdo_snowflake.so -m | grep pdo_snowflake
          working-directory: /Users/runner/work/ATA-POC-ODBC/ATA-POC-ODBC/pdo_snowflake
