# This is a basic workflow to help you get started with Actions
# https://github.com/snowflakedb/pdo_snowflake/blob/master/README.rst

name: snowflake-windows

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4.13
          extensions: pdo, json

      - name: get source
        run: git clone https://github.com/snowflakedb/pdo_snowflake.git c:\pdo_snowflake
      
      - name: setup php sdk 1
        run: git clone https://github.com/Microsoft/php-sdk-binary-tools.git c:\php-sdk && cd c:\php-sdk && git checkout php-sdk-2.2.0
             
      - name: check env
        run: set
        shell: cmd
     
      - name: check source
        run: dir c:\pdo_snowflake
        shell: cmd
      
      - name: build
        run: .\scripts\run_build_pdo_snowflake.bat x64 Release VS15 7.4.13 c:\php-sdk
        shell: cmd
        working-directory:  c:\pdo_snowflake
       
