# This is a basic workflow to help you get started with Actions

name: snowflake-macos

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #- uses: actions/checkout@v2
        - name: setup php
          uses: shivammathur/setup-php@v2
          with:
            php-version: 7.2
            extensions: pdo, json
        
        - name: check env
          run: which php
            
        #- name: get source
        #  run: git clone https://github.com/snowflakedb/pdo_snowflake.git /usr/pdo_snowflake
        
        # Runs a single command using the runners shell
        #- name: Build PDO Driver
        #  run: |
        #    export RUN_COVERAGE=1
        #    export PHP_HOME=/usr
        #    which php
        #    pwd
        #    ./scripts/build_pdo_snowflake.sh
        #    $PHP_HOME/bin/php -dextension=modules/pdo_snowflake.so -m | grep pdo_snowflake
        #  working-directory: /usr/pdo_snowflake
