# This is a basic workflow to help you get started with Actions
# https://github.com/snowflakedb/pdo_snowflake/blob/master/README.rst

name: snowflake-windows

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: setup php
      #  uses: shivammathur/setup-php@v2
      #  with:
      #    php-version: 7.4.13
      #    extensions: pdo, json

      - name: get source
        run: git clone https://github.com/snowflakedb/pdo_snowflake.git c:\pdo_snowflak
      
      - name: setup php sdk
        #run: git clone https://github.com/Microsoft/php-sdk-binary-tools.git c:\php-sdk && cd c:\php-sdk && git checkout php-sdk-2.2.0
        run: .\scripts\setup_php_sdk.bat x64 Release VS15 C:\php-sdk
        shell: cmd
        working-directory:  c:\pdo_snowflake
        
      - name: setup php
        #run: git clone https://github.com/Microsoft/php-sdk-binary-tools.git c:\php-sdk && cd c:\php-sdk && git checkout php-sdk-2.2.0
        run: .\scripts\run_setup_php.bat x64 Release VS15 7.2.24 C:\php-sdk
        shell: cmd
        working-directory:  c:\pdo_snowflake
      
      - name: check env
        run: set
        shell: cmd
      
      - name: build
        run: set PHP_HOME=c:\tools\php && .\scripts\run_build_pdo_snowflake.bat x64 Release VS15 7.4.13 c:\php-sdk
        shell: cmd
        working-directory:  c:\pdo_snowflake
    
      - name: check
        run: dir c:\php-sdk /S
        shell: cmd
        
      - name: check file
        run: c:\tools\php\php.exe -dextension=-dextension=ext\php_pdo_snowflake.dll -m
        working-directory:  c:\pdo_snowflake
