# This is a basic workflow to help you get started with Actions

name: strategy_poc

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      SEN_LABEL:
        description: 'SimbaEngineSDK label'     
        required: true
        default: '__head__'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: centos:${{ matrix.os }}
    strategy:
      matrix:
        os: [centos6, centos7, centos8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: run commands
        run: |
          cat /etc/*elease
          echo "SEN_LABEL: ${{ github.event.inputs.SEN_LABEL }}"
