# This is a basic workflow to help you get started with Actions

name: test windows

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    tags:
      - '*'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
        
    - name: Check cwd
      run: pwd
      
    - name: Check files
      run: ls
      
    - name: checnk maven
      run: mvn --version
      
    - name: Build with Maven
      run: mvn -B package --file ./test-app/pom.xml
      
    - name: Run test app
      run: java -cp test-app/target/test-app-1.0-SNAPSHOT.jar com.ata.app.App
  
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build artifacts
        path: test-app/target/test-app-1.0-SNAPSHOT.jar
        
    - name: renmae
      run: rename .\test-app\target\test-app-1.0-SNAPSHOT.jar test-app-1.0-SNAPSHOT-windows.jar
      shell: cmd
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files:
            test-app/target/test-app/target/test-app-1.0-SNAPSHOT-windows.jar
      env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
