# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: "c:\Program Files (x86)\Microsoft Visual Studio"\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64\dumpbin
        shell: cmd
