# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: pdo, json
        env:
          phpts: ts
      
      - name: get source
        run: git clone https://github.com/snowflakedb/pdo_snowflake.git c:\pdo_snowflake
        shell: cmd
      
      - name: setup php sdk
        run: .\scripts\setup_php_sdk.bat x64 Release VS15 c:\php-sdk
        shell: cmd
        working-directory: c:\pdo_snowflake
        
      #- name: setup php
        #uses: shivammathur/setup-php@v2
        #with:
        #  php-version: 7.2
        #  extensions: pdo, json
      #  run: .\scripts\run_setup_php.bat x64 Release VS15 7.2.24 c:\php-sdk
      #  shell: cmd
      #  working-directory:  c:\pdo_snowflake
        
      - name: check php
        run: dir c:\tools\php\
        shell: cmd
      
      - name: check php config
        run: type c:\tools\php\php.ini
        shell: cmd
      
      - name: check file
        run: c:\tools\php\php.exe -v
        working-directory:  c:\tools\php
        shell: cmd
       
      - name: load an extension
        run: c:\tools\php\php.exe -dextension=pdo_mysql -m
        shell: cmd
