# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    tags:
      - '*'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: test
        run: echo triggered by creating a tag
        shell: cmd
      
      - name: test
        run: set
        shell: cmd
          
